name: Build and run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23.2
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: go get
        run: |
          dirs=$(go list -f '{{.Dir}}' -m )
           for dir in ${dirs[@]}; do
             cd "$dir"
             go mod tidy
           done

      - name: test
        run: |
          echo secrets.GH_ACTIONS_GCP_SA_STAGING > staging-creds.json
          dirs=$(go list -f '{{.Dir}}' -m )
            for dir in ${dirs[@]}; do
            go test -race -v -coverprofile=$dir/c.out $dir/...
          done
